### ISSUE TITLE
transaction flow order

### ISSUE THREAD

**Issue by hauchu1998** [blockworks-foundation/mangolana#2]
https://github.com/blockworks-foundation/mangolana/blob/23cff01be4427212d4148a4d3a2a056bb4dff6ef/src/transactions.ts#L391C3-L391C96

I have a question that if I'm using `sendSignAndConfirmTransactions` to design a transaction flow as the description `[Parallel, Sequential, Parallel]`. Will the Sequestial txs wait till the first Parallel txs are completed to process?

**Comment by abrzezinski94** [comment]
It should use the order of what user inputs if it’s otherwise for you let me know will fix it
